
const defaultPath = 'http://localhost:9000'
const path = process.env.BACKSTOP_BASE_URL ? process.env.BACKSTOP_BASE_URL : defaultPath;

module.exports = {
	id: 'backstop_default',
	viewports: [
		{
			label: 'phone',
			width: 320,
			height: 480,
		},
		{
			label: 'desktop',
			width: 1920,
			height: 1080,
		},
	],
	onBeforeScript: 'puppet/onBefore.js',
	onReadyScript: 'puppet/onReady.js',
	scenarios: [
		{
			label: 'PCP Homepage',
			cookiePath: 'testing/backstop/data/engine_scripts/cookies.json',
			url: path,
			referenceUrl: '',
			readyEvent: '',
			readySelector: '',
			delay: 10000,
			hideSelectors: [],
			removeSelectors: [],
			hoverSelector: '',
			clickSelector: '',
			postInteractionWait: 0,
			selectors: [],
			selectorExpansion: true,
			expect: 0,
			misMatchThreshold: 0.5,
			requireSameDimensions: true,
		},
		{
			label: 'Members',
			cookiePath: 'testing/backstop/data/engine_scripts/cookies.json',
			url: path + '/members/',
			referenceUrl: '',
			readyEvent: '',
			readySelector: '',
			delay: 10000,
			hideSelectors: [],
			removeSelectors: [],
			hoverSelector: '',
			clickSelector: '',
			postInteractionWait: 0,
			selectors: [],
			selectorExpansion: true,
			expect: 0,
			misMatchThreshold: 0.5,
			requireSameDimensions: true,
		},
		{
			label: 'About',
			cookiePath: 'testing/backstop/data/engine_scripts/cookies.json',
			url: path + '/about/',
			referenceUrl: '',
			readyEvent: '',
			readySelector: '',
			delay: 10000,
			hideSelectors: [],
			removeSelectors: [],
			hoverSelector: '',
			clickSelector: '',
			postInteractionWait: 0,
			selectors: [],
			selectorExpansion: true,
			expect: 0,
			misMatchThreshold: 0.5,
			requireSameDimensions: true,
		},
		{
			label: 'Reports',
			cookiePath: 'testing/backstop/data/engine_scripts/cookies.json',
			url: path + '/reports/',
			referenceUrl: '',
			readyEvent: '',
			readySelector: '',
			delay: 10000,
			hideSelectors: [],
			removeSelectors: [],
			hoverSelector: '',
			clickSelector: '',
			postInteractionWait: 0,
			selectors: [],
			selectorExpansion: true,
			expect: 0,
			misMatchThreshold: 0.5,
			requireSameDimensions: true,
		},
		{
			label: 'Report Subnav',
			cookiePath: 'testing/backstop/data/engine_scripts/cookies.json',
			url: path + '/reports/2023/opportunities/',
			referenceUrl: '',
			readyEvent: '',
			readySelector: '',
			delay: 10000,
			hideSelectors: [],
			removeSelectors: [],
			hoverSelector: '',
			clickSelector: '',
			postInteractionWait: 0,
			selectors: [],
			selectorExpansion: true,
			expect: 0,
			misMatchThreshold: 0.5,
			requireSameDimensions: true,
		},
		{
			label: 'Blogs',
			cookiePath: 'testing/backstop/data/engine_scripts/cookies.json',
			url: path + '/about/blogs/',
			referenceUrl: '',
			readyEvent: '',
			readySelector: '',
			delay: 10000,
			hideSelectors: [],
			removeSelectors: [],
			hoverSelector: '',
			clickSelector: '',
			postInteractionWait: 0,
			selectors: [],
			selectorExpansion: true,
			expect: 0,
			misMatchThreshold: 0.5,
			requireSameDimensions: true,
		},
		{
			label: 'Search',
			cookiePath: 'testing/backstop/data/engine_scripts/cookies.json',
			/* Obscure search term and small pageunit to get a good test that rarely changes */
			url: path + '/search?swKeyword=connectedhealth&page=1&pageunit=5',
			referenceUrl: '',
			readyEvent: '',
			readySelector: '',
			delay: 10000,
			hideSelectors: [],
			removeSelectors: [],
			hoverSelector: '',
			clickSelector: '',
			postInteractionWait: 0,
			selectors: [],
			selectorExpansion: true,
			expect: 0,
			misMatchThreshold: 0.5,
			requireSameDimensions: true,
		},
	],
	paths: {
		bitmaps_reference: 'testing/backstop/data/bitmaps_reference',
		bitmaps_test: 'testing/backstop/data/bitmaps_test',
		engine_scripts: 'testing/backstop/data/engine_scripts',
		html_report: 'testing/backstop/data/html_report',
		ci_report: 'testing/backstop/data/ci_report',
	},
	report: ['browser'],
	engine: 'puppeteer',
	engineOptions: {
		args: ['--no-sandbox'],
	},
	asyncCaptureLimit: 5,
	asyncCompareLimit: 50,
	debug: false,
	debugWindow: false,
};
