name: Deploy to Production
on:
  release:
    types: [released]

jobs:
  
  call-workflow-deploy:
    uses: ./.github/workflows/deploy-site.yml
    with:
      environment: Prod
      build_name: pcp-prod
      use_artifact: true
    secrets: inherit