name: Build and Deploy to Test
on:
  workflow_dispatch:

jobs:
  
  call-workflow-build:
    uses: ./.github/workflows/build-site.yml
    with: 
      environment: Test
    secrets: inherit
  
  call-workflow-deploy:
    uses: ./.github/workflows/deploy-site.yml
    with:
      environment: Test
      build_name: pcp-test
    ## This job depends on build completing
    needs: call-workflow-build
    secrets: inherit